config/routes.rb
CustomerKonnect::Application.routes.draw do
  root :to => "shoppers#index", as: "home", via: "get"
  match '/businesses', to: 'businesses#index', via: "get", as: :business
  match '/businesses', to: 'businesses#index', via: "patch", as: :business_patch
  match '/businesses/show/:id', to: 'businesses#show', via: "get",as: :show_business
  match '/businesses/new', to: 'businesses#new', via: "get",as: :signup
  match '/businesses/:id/edit', to: 'businesses#edit', via: "get", as: :edit_business
  match '/businesses', to: 'businesses#create', via: "post"
  match '/businesses/update/:id', to: 'businesses#update',  via: "put"
  match '/businesses/destroy/:id', to: 'businesses#destroy', via: "delete", as: :destroy_business
  match '/businesses/feedback/:id', to: 'businesses#feedback', via: "get", as: :get_feedback_business
  match 'shoppers/contact', to: 'shoppers#contact', via: "get", as: :contact
  match 'shoppers/about', to: 'shoppers#about', via: "get", as: :about
  match 'businesses/reply', to: 'businesses#reply', via: "get", as: :reply
  get "feedback/new", as: :give_feedback
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  resources :feedback
  resources :sessions
end

app/models/business.rb
class Business < ActiveRecord::Base
	has_many :feedbacks

  
  attr_accessor :password
  before_save :encrypt_password
  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
	belongs_to :shopper
	belongs_to :business
	accepts_nested_attributes_for :shopper
end

app/models/shopper.rb
class Shopper < ActiveRecord::Base
	has_many :feedbacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  helper_method :current_user
  before_action :current_user

  protect_from_forgery with: :exception

  layout 'slate'

  def current_user
  	@current_user ||= Business.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: [:show, :edit, :update, :destroy, :feedback]

  # GET /businesses
  # GET /businesses.json
  def index
    @businesses = Business.all
  end

  # GET /businesses/1
  # GET /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  def login
  end
  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses
  # POST /businesses.json
  def create
    @business = Business.new(business_params)

    respond_to do |format|
      if @business.save
        format.html { redirect_to action: "index", notice: 'Business was successfully created.' }
        format.json { render action: 'show', status: :created, location: @business }
      else
        format.html { render action: 'new' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1
  # PATCH/PUT /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to show_business_path(@business), notice: 'Business was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1
  # DELETE /businesses/1.json
  def destroy
    @business.destroy
    respond_to do |format|
      format.html { redirect_to business_path }
      format.json { head :no_content }
    end
  end

  def feedback
      @feedbacks = Feedback.where(business_id: params[:id])
      @business = Business.find(params[:id])
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business
      @business = Business.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_params
      params.require(:business).permit(:name, :address, :email,:password)
    end
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
	def new
		@feedback = Feedback.new
		@business_options = Business.all.map do |b|
			[b.name, b.id]  		
		end
	end

	def create
		@shopper = Shopper.find_or_initialize_by(email: params["feedback"]["shoppers"]["email"])
		@shopper.update_attributes(phone_number: params["feedback"]["shoppers"]["phone_number"])
		session[:value] = true
		session[:shopper_id] = @shopper.id

		@feedback = Feedback.create(feedback_params)
		@feedback.update_attributes(shopper: @shopper)
		redirect_to :feedback_index

	end

	def index
		@shopper = Shopper.find(session[:shopper_id])
		@feedbacks = Feedback.where(shopper: @shopper)
	end

	def feedback_params
		params.require(:feedback).permit(:description, :business_id, :shopper)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = Business.authenticate(params[:email],params[:password]);
    if @user
      session[:user_id] = @user.id;
      redirect_to get_feedback_business_path(@user)
    else
      error[:base] = "Wrong Log In !! Please try again"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_url, :notice => "Logged out!"
  end

end
 

app/controllers/shoppers_controller.rb
class ShoppersController < ApplicationController
  def index
  	session[:shopper_id] = nil
  end

  def contact
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
	
	private

		def current_user
  			@current_user ||= Business.find(session[:user_id]) if session[:user_id]
		end

end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/feedback_helper.rb
module FeedbackHelper
end

app/helpers/shoppers_helper.rb
module ShoppersHelper
end

app/views/businesses/_form.html.erb
<%= form_for(@business) do |f| %>
  <% if @business.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@business.errors.count, "error") %> prohibited this business from being saved:</h2>

      <ul>
      <% @business.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>

<%= render 'form' %>

<%= link_to 'Show', show_business_path(@business) %> |
<%= link_to 'Back', businesses_path %>

app/views/businesses/feedback.html.erb
<div id="feedback" style="margin-left: 80px">
<h1>Listing Feedback</h1>


    <% @feedbacks.each do |feedback| %>
    <table>
  <tbody>
      <tr>
        <td><b>Business name:</b> <%= @business.name %></td>
      </tr>
      <tr>
        
        <td><b>Feedback Description:</b> <%= feedback.description %></td>
      </tr>
      <tr>
        <td><b>Feedback given at:</b> <%= feedback.created_at.to_s(:short) %></td>
        
      </tr>
      <tr>
        <td><%= link_to 'Reply', reply_path %></td>
      </tr>
      <br>

    <% end %>
  </tbody>
</table>
<br>
 <td><%= link_to 'Back', show_business_path(@business) %></td>
<br>
</div>

app/views/businesses/index.html.erb
<div style="margin-left: 80px">
  <h1>Listing businesses</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>Email</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @businesses.each do |business| %>
        <tr>
          <td>&nbsp;<%= business.name %>&nbsp;</td>
          <td>&nbsp;<%= business.address %>&nbsp;</td>
          <td>&nbsp;<%= business.email %>&nbsp;</td>
          <td>&nbsp;<%= link_to 'Show', show_business_path(business) %>&nbsp;</td>
          <td>&nbsp;<%= link_to 'Edit', edit_business_path(business) %>&nbsp;</td>
          
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

</div>

app/views/businesses/new.html.erb
<div style="margin-left: 80px">
	<h1>New business</h1>

	<%= render 'form' %>

	<%= link_to 'Back', businesses_path %>
</div>

app/views/businesses/reply.html.erb
<div style="margin-left: 80px">
	<h1>Reply to feedback</h1>
	
	<p><%= text_area_tag :description %></p>
	<p><%= button_tag "Submit" %></p>
</div>

app/views/businesses/show.html.erb
<div style="margin-left: 80px">
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Name:</strong>
	  <%= @business.name %>
	</p>

	<p>
	  <strong>Address:</strong>
	  <%= @business.address %>
	</p>

	<p>
	  <strong>Email:</strong>
	  <%= @business.email %>
	</p>


	<%= link_to 'Edit', edit_business_path(@business) %>
	<!--<%= link_to 'Back', businesses_path %>-->
	<!--<%= link_to 'See feedback', get_feedback_business_path(@business) %>-->
</div>

app/views/feedback/index.html.erb
<div style="margin-left: 80px">
	<% @feedbacks.each do |feedback| %>
	<p>Feedback Description: <%= feedback.description %></p>
	<p>Email: <%= feedback.shopper.email %></p>
	<p>Business Name: <%= feedback.business.name %></p>
	<% end %>
	<p><%= link_to 'Home', home_path %>&nbsp;|&nbsp;<%= link_to 'New feedback', new_feedback_path %></p>
</div>

app/views/feedback/new.html.erb
<div style="margin-left: 80px">
	<h1>New feedback</h1>
	<div class="select-business"></div>

	<%= form_for @feedback, url: {action: "create"}, html: {class: "create-feedback"} do |f| %>
	<p><%= f.label "Choose a business" %></p>
	<p><%= f.select(:business_id, options_for_select(@business_options)) %></p>
	<p>Please give us your feedback and we'll take it to the business owner directly. Your anonymity will be completely protected</p>
	<p><%= f.text_area :description, size: "60x12" %></p>
	<p><%= f.fields_for :shoppers do |ff| %></p>
	<p>Your email: <%= ff.text_field :email  %></p>
	<p>Your phone number: <%= ff.text_field :phone_number %></p>
	<% end %>
	<p><%= f.submit "Submit" %></p>
	<% end %>
</div>

app/views/layouts/slate.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "customer_konnect" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "slate", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=<%= home_path %>>Customer Konnect</a>       
        
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
           <!-- <li class="active"><a href=<%= home_path %>>Home</a></li>-->
            <li><a href=<%= about_path %>>About</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Business <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <% if @current_user == nil %>
                  <li><a href="<%= log_in_path  %>">Login</a></li>
                  <%end%>
                  <% if @current_user %>
                  <li><a href="<%= get_feedback_business_path(@current_user) %>">Feedbacks</a></li>
                  <li><a href="<%= log_out_path %>">Logout</a></li>

                  <%end%>
                  <li><a href="<%= signup_path%>">Signup</a></li>
                </ul>
            </li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Shoppers <b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><a href="<%= give_feedback_path%>">Give Feeback</a></li>
                  <li><a href="<%= business_path%>">List of Businesses</a></li>
                </ul>
                <li><a href=<%= contact_path %>>Contact</a></li>
            
            </li>
          </ul>
        </div><!--/.nav-collapse -->
          
        
        
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div style="margin-top: 80px">
    <%= yield %>
    </div>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "slate" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/shoppers/about.html.erb
<div class="jumbotron">
        <h1>Wondering who we are?</h1>
        <p>We are a bunch of strangers who met at the Startup Weekend Delhi on 19th Sept 2014 and decided to work together on improving the current customer feedback systems for businesses around the world.</p>
        <p><b>Team</b>
        <ul>
        	<li>Gaurav Mittal</li>
        	<li>Siddhartha Gupta</li>
        	<li>Gaurav Arora</li>
        	<li>Raghav Malik</li>
        	<li>Samir Sethi</li>
        	<li>Manuj Maurya</li>
        	<li>Arun Jolly Joseph</li>
        </ul>
        </p>
      </div>

app/views/shoppers/contact.html.erb
<div class="jumbotron">
        <h1>Want to talk to us?</h1>
        <p>You can reach us at sid.india@gmail.com</p>
        <p>We promise your mails will be read!</p>
      </div>

app/views/shoppers/index.html.erb
<div class="jumbotron">
        <h1>Welcome to Customer Konnect!</h1>
        <p>Give your feedback directly to a store owner <b>anonymously</b> through a 1 to 1 private channel. 
        We ensure that your feedback reaches the right people, whether it be positive, negative or suggestive. </p>
        <p>Don't hold back, you may just win some amazing rewards!!</p>
      <%= link_to "Sounds good! I want to share my feedback!", new_feedback_path %>
      </div>